ALTER TABLE customers ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE customers ADD COLUMN IF NOT EXISTS created_by TEXT NOT NULL DEFAULT 'System';
ALTER TABLE customers ADD COLUMN IF NOT EXISTS updated_by TEXT NOT NULL DEFAULT 'System';

ALTER TABLE technicians ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE technicians ADD COLUMN IF NOT EXISTS created_by TEXT NOT NULL DEFAULT 'System';
ALTER TABLE technicians ADD COLUMN IF NOT EXISTS updated_by TEXT NOT NULL DEFAULT 'System';

ALTER TABLE inventory_parts ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE inventory_parts ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE inventory_parts ADD COLUMN IF NOT EXISTS created_by TEXT NOT NULL DEFAULT 'System';
ALTER TABLE inventory_parts ADD COLUMN IF NOT EXISTS updated_by TEXT NOT NULL DEFAULT 'System';

ALTER TABLE invoices ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS created_by TEXT NOT NULL DEFAULT 'System';
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS updated_by TEXT NOT NULL DEFAULT 'System';

ALTER TABLE work_items ADD COLUMN IF NOT EXISTS created_by TEXT NOT NULL DEFAULT 'System';
ALTER TABLE work_items ADD COLUMN IF NOT EXISTS updated_by TEXT NOT NULL DEFAULT 'System';

ALTER TABLE users ADD COLUMN IF NOT EXISTS created_by TEXT NOT NULL DEFAULT 'System';
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_by TEXT NOT NULL DEFAULT 'System';
